### ISSUE TITLE
Nothing happens for `master` branch (as opposed to `main` branch)

### ISSUE THREAD

**Issue by page200** [coezbek/github-fork-bookmarklet#1] opened 2024-11-22 12:26 UTC
Thank you for these bookmarklets!

When using the first bookmarklet on (some or all) repos whose name contains `.`, nothing appears on the page nor in the console. I tried Chrome while logged into GitHub, and Firefox while logged off. Example URL: https://github.com/Kotlin/kotlinx.coroutines/network/members

**Comment by coezbek** [comment] 2024-11-22 12:50
The issue is with the name of the main branch. kotlinx uses `master` but the bookmarketlet assumes the name is `main`. I have to see if there is a way to extract the correct name of the default branch.

**Comment by coezbek** [comment] 2024-11-22 13:26
Fixed in https://github.com/coezbek/github-fork-bookmarklet/commit/e8de6f37ab7bcfb41316c64132addd3ca731694f

Thank you for the report!

**Closed as completed by coezbek** 2024-11-22 13:26 UTC

**Comment by page200** [comment] 2024-11-22 17:21
Thank you!
